image: "python:3.9"


before_script:
  - python --version
  - pip install -r requirements.txt


stages:
  - Test
  - Deploy


unit_test:
  stage: Test
  only:
    - branches
  except:
    - main
  script:
    - pwd
    - ls -l
    - python tests/main.py


run_python:
  stage: Deploy
  script:
    - pwd
    - ls -l
    - python src/main.py 


pages:
  stage: Deploy
  script:
  - pwd
  - ls -l
  - pip install -U sphinx
  - pip install sphinx_rtd_theme
  - pip install myst-parser
  - cd docs/
  - make html
  - mv _build/html public
  artifacts:
    paths:
    - public
  only:
  - main