image: "python:3.9"


before_script:
  - python --version
  - pip install -r requirements.txt


stages:
  - Test
  - Code deploy
  - Pages deploy


unit_test:
  stage: Test
  only:
    - branches
  except:
    - main
  script:
    - pwd
    - ls -l
    - python tests/main.py


run_python:
  stage: Code deploy
  script:
    - pwd
    - ls -l
    - python src/main.py 


pages:
  stage: Page deploy
  script:
  - pwd
  - ls -l
  - cd docs/
  - ls -l
  - pip install sphinx_rtd_theme
  - pip install myst-parser
  - sphinx-build -b html . ../public
  - cd ../
  artifacts:
    paths:
    - public
