image: "python:3.9"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Test
  - Deploy


unit_test:
  stage: Test
  only:
    - branches
  except:
    - master
  script:
    - pwd
    - ls -l
    - python tests/main.py


run_python:
  stage: Deploy
  script:
    - pwd
    - ls -l
    - python src/main.py 

pages:
  stage: Deploy
  script:
  - mv docs/build/html/ public/
  - pip install -U sphinx
  - pip install sphinx_rtd_theme
  - pip install myst-parser
  - sphinx-build -d _build/doctrees . _build/html
  - mv _build/html public
  artifacts:
    paths:
    - public
  only:
  - master