image: "python:3.9"
before_script:
  - python --version
  - pip install -r requirements.txt
stages:
  - Static Analysis
  - Test
run_python:
  stage: Static Analysis
  script:
  - pwd
  - ls -l
  - python main.py 
unit_test:
  stage: Test
  script:
  - pwd
  - ls -l
  - export PYTHONPATH="$PYTHONPATH:."
  - python -c "import sys;print(sys.path)"
  - pytest
