*******************************************************************************
      subroutine symelem
      implicit real*8 (a-h,o-z)
      include 'param.inc'     
      character*2 sym, element
      !common/names/iznu(max_atom),element(max_atom),sym(120),xbox,mspin
      !common/elemente/element(max_atom),mspin
      common/names/iznu(max_atom),sym(120),xbox

      sym(1) ='H'
      sym(2) ='He'
      sym(3) ='Li'
      sym(4) ='Be'
      sym(5) ='B'
      sym(6) ='C'
      sym(7) ='N'
      sym(8) ='O'
      sym(9) ='F'
      sym(10)='Ne'
      sym(11)='Na'
      sym(12)='Mg'
      sym(13)='Al'
      sym(14)='Si'
      sym(15)='P'
      sym(16)='S'
      sym(17)='Cl'
      sym(18)='Ar'
      sym(19)='K'
      sym(20)='Ca'
      sym(21)='Sc'
      sym(22)='Ti'
      sym(23)='V'
      sym(24)='Cr'
      sym(25)='Mn'
      sym(26)='Fe'
      sym(27)='Co'
      sym(28)='Ni'
      sym(29)='Cu'
      sym(30)='Zn'
      sym(31)='Ga'
      sym(32)='Ge'
      sym(33)='As'
      sym(34)='Se'
      sym(35)='Br'
      sym(36)='Kr'
      sym(37)='Rb'
      sym(38)='Sr'
      sym(39)='Y'
      sym(40)='Zr'
      sym(41)='Nb'
      sym(42)='Mo'
      sym(43)='Tc'
      sym(44)='Ru'
      sym(45)='Rh'
      sym(46)='Pd'
      sym(47)='Ag'
      sym(48)='Cd'
      sym(49)='In'
      sym(50)='Sn'
      sym(51)='Sb'
      sym(52)='Te'
      sym(53)='I'
      sym(54)='Xe'
      sym(55)='Cs'
      sym(56)='Ba'
      sym(57)='La'
      sym(58)='Ce'
      sym(59)='Pr'
      sym(60)='Nd'
      sym(61)='Pm'
      sym(62)='Sm'
      sym(63)='Eu'
      sym(64)='Gd'
      sym(65)='Tb'
      sym(66)='Dy'
      sym(67)='Ho'
      sym(68)='Er'
      sym(69)='Tm'
      sym(70)='Yb'
      sym(71)='Lu'
      sym(72)='Hf'
      sym(73)='Ta'
      sym(74)='W'
      sym(75)='Re'
      sym(76)='Os'
      sym(77)='Ir'
      sym(78)='Pt'
      sym(79)='Au'
      sym(80)='Hg'
      sym(81)='Tl'
      sym(82)='Pb'
      sym(83)='Bi'
      sym(84)='Po'
      sym(85)='At'
      sym(86)='Rn'
      sym(87)='Fr'
      sym(88)='Ra'
      sym(89)='Ac'
      sym(90)='Th'
      sym(91)='Pa'
      sym(92)='U'
      sym(93)='Np'
      sym(94)='Pu'
      sym(95)='Am'
      sym(96)='Cm'
      sym(97)='Bk'
      sym(98)='Cf'
      sym(99)='Es'
      sym(100)='Fm'
      sym(101)='Md'
      sym(102)='No'
      sym(103)='Lr'
      sym(104)='Rf'
      sym(105)='Db'
      sym(106)='Sg'
      sym(107)='Bh'
      sym(108)='Hs'
      sym(109)='Mt'
      sym(110)='Un'
      sym(111)='Pl'
      sym(112)='Da'
      sym(113)='Tf'
      sym(114)='Eo'
      sym(115)='Me'
      sym(116)='Nc'
      sym(117)='El'
      sym(118)='On'


      return
      end
*******************************************************************************	
