name: AMCESS: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]


    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
          pip install ruff pytest tox

      # - name: Lint with ruff
      #   run: |
          ## stop the build if there are Python syntax errors or undefined names
          # ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
          ## default set of ruff rules with GitHub Annotations
          # ruff --format=github --target-version=py37 .
      #   continue-on-error: true

      - name: Test with pytest
        run: |
          # pytest
          tox -e py


